export {default as Header} from './Header/Header'
export {default as HeroSection} from './Hero_Section/HeroSection'
export {default as AboutUs} from './About_us/AboutUs'
export {default as Clients} from './Clients/Clients'
export {default as Testimonials} from './Testimonials/Testimonials'
export {default as Faqs} from './Faqs/Faqs'
export {default as Subscribe} from './Subscribe/Subscribe'
export {default as Footer} from './Footer/Footer'
